
services:
  news-aggregation_server:
    build:
      context: ./services/news-aggregation_server
    ports:
      - "3002:3002"
    env_file:
      - ./services/news-aggregation_server/.env
    depends_on:
      - mongo
    networks:
      - app-network
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=news-server"
      - "dapr.io/app-port=3002"
    
  user_server:
    build:
      context: ./services/user_server
    ports:
      - "3001:3001"
    env_file:
      - ./services/user_server/.env
    depends_on:
      - mongo
    networks:
      - app-network
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=user-server"
      - "dapr.io/app-port=3001"

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - user_server
    labels:
      - "dapr.io/enabled=false"

  mongo:
    image: mongo:latest
    restart: always  
    command: mongod --bind_ip_all
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    labels:
      - "dapr.io/enabled=false"
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

# Reference to the environment file for all services
#env_file:
 
 # - .env  # הגדרת קובץ env כללי
