
services:
  # News Aggregation Service
  news-aggregation_server:
    build:
      context: ./services/news-aggregation_server
    ports:
      - "3002:3002"
    env_file:
      - ./services/news-aggregation_server/.env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=news-aggregation_server"
      - "dapr.io/app-port=3002"
  
  # User Service
  user_server:
    build:
      context: ./services/user_server
    ports:
      - "3001:3001"
    env_file:
      - ./services/user_server/.env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=user_server"
      - "dapr.io/app-port=3001"

  # Client (Frontend)
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - user_server
    labels:
      - "dapr.io/enabled=false"

  # MongoDB Database
  mongo:
    image: mongo:latest
    restart: always  
    command: mongod --bind_ip_all
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    labels:
      - "dapr.io/enabled=false"
    ports:
      - "27017:27017"

  # RabbitMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ message broker
      - "15672:15672" # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network
    labels:
      - "dapr.io/enabled=false"

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
